0: [0, 0, 0, 0]  # None
1: [0, 1, 0, 0]  # Road
2: [0, 0, 1, 0]  # SideWalks
3: [0, 0, 1, 0]  # Buildings
4: [0, 0, 1, 0]  # Walls
5: [0, 0, 1, 0]  # Fences
6: [0, 0, 1, 0]  # Poles
7: [1, 0, 0, 0]  # TrafficLight
8: [1, 0, 0, 0]  # TrafficSigns
9: [0, 0, 1, 0]  # Vegetation
10: [0, 0, 0, 0]  # Terrain
11: [0, 0, 0, 0]  # Sky
12: [0, 0, 0, 1]  # Pedestrians
13: [0, 0, 0, 1]  # Rider
14: [0, 0, 0, 1]  # Car
15: [0, 0, 0, 1]  # Truck
16: [0, 0, 0, 1]  # Bus
17: [0, 0, 0, 1]  # Train
18: [0, 0, 0, 1]  # Motorcycle
19: [0, 0, 0, 1]  # Bicycle
20: [0, 0, 1, 0]  # Static
21: [0, 0, 0, 1]  # Dynamic
22: [0, 0, 1, 1]  # Other
23: [0, 0, 0, 0]  # Water
24: [1, 0, 0, 0]  # RoadLines
25: [0, 0, 0, 0]  # Ground
26: [0, 1, 0, 0]  # Bridge
27: [0, 1, 0, 0]  # RailTrack
28: [0, 1, 0, 0]  # GuardRail
