# This palette maps the tags to the following layers: roadline and traffic signs, drivable area, static obstacle, dynamic obstacle
color_map:
- [1, 0, 0, 0]    # None
- [0, 1, 0, 0]    # Road
- [0, 0, 1, 0]    # SideWalks
- [0, 0, 1, 0]    # Buildings
- [0, 0, 1, 0]    # Walls
- [0, 0, 1, 0]    # Fences
- [0, 0, 1, 0]    # Poles
- [1, 0, 0, 0]    # TrafficLight
- [1, 0, 0, 0]    # TrafficSigns
- [0, 0, 1, 0]    # Vegetation
- [0, 0, 1, 0]    # Terrain
- [0, 0, 1, 0]    # Sky
- [0, 0, 0, 1]    # Pedestrians
- [0, 0, 0, 1]    # Rider
- [0, 0, 0, 1]    # Car
- [0, 0, 0, 1]    # Truck
- [0, 0, 0, 1]    # Bus
- [0, 0, 0, 1]    # Train
- [0, 0, 0, 1]    # Motorcycle
- [0, 0, 0, 1]    # Bicycle
- [0, 0, 1, 0]    # Static
- [0, 0, 0, 1]    # Dynamic
- [0, 0, 1, 0]    # Other
- [0, 0, 1, 0]    # Water
- [1, 0, 0, 0]    # RoadLines
- [0, 1, 0, 0]    # Ground
- [0, 1, 0, 0]    # Bridge
- [0, 0, 1, 0]    # RailTrack
- [0, 0, 1, 0]    # GuardRail
