camera_front:
  id: camera_front
  type: sensor.camera.rgb
  blueprint: sensor.camera.rgb
  blueprint_attributes:
    image_size_x: 640
    image_size_y: 480
    fov: 120
  x: 0.2
  y: 0.0
  z: 1.8
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  width: 640
  height: 480
  fov: 120

camera_left:
  id: camera_left
  type: sensor.camera.rgb
  blueprint: sensor.camera.rgb
  blueprint_attributes:
    image_size_x: 640
    image_size_y: 480
    fov: 120
  x: -0.1
  y: -0.4
  z: 1.8
  roll: 0.0
  pitch: -15.0
  yaw: -90.0
  width: 640
  height: 480
  fov: 120

camera_right:
  id: camera_right
  type: sensor.camera.rgb
  blueprint: sensor.camera.rgb
  blueprint_attributes:
    image_size_x: 640
    image_size_y: 480
    fov: 120
  x: -0.1
  y: 0.4
  z: 1.8
  roll: 0.0
  pitch: -15.0
  yaw: 90.0
  width: 640
  height: 480
  fov: 120

camera_rear:
  id: camera_rear
  type: sensor.camera.rgb
  blueprint: sensor.camera.rgb
  blueprint_attributes:
    image_size_x: 640
    image_size_y: 480
    fov: 120
  x: -0.5
  y: 0.0
  z: 1.8
  roll: 0.0
  pitch: 0.0
  yaw: 180.0
  width: 640
  height: 480
  fov: 120

lidar:
  id: lidar
  type: sensor.lidar.ray_cast
  blueprint: sensor.lidar.ray_cast
  blueprint_attributes:
    range: 50
    channels: 32
    points_per_second: 100000
    rotation_frequency: 10.0
  x: 0.0
  y: 0.0
  z: 1.8
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  range: 50
  channels: 32
  points_per_second: 100000
  rotation_frequency: 10.0

radar_test:
  id: radar_test
  type: sensor.other.radar
  blueprint: sensor.other.radar
  blueprint_attributes:
    range: 100
    points_per_second: 1500
  x: 0.0
  y: 0.0
  z: 2.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  points_per_second: 1500
  range: 100

imu:
  id: imu
  type: sensor.other.imu
  blueprint: sensor.other.imu
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  sensor_tick: 0.05

imu_test:
  id: imu_test
  type: sensor.other.imu
  blueprint: sensor.other.imu
  blueprint_attributes:
    noise_accel_stddev_x: 0.001
    noise_accel_stddev_y: 0.001
    noise_accel_stddev_z: 0.015
    noise_gyro_stddev_x: 0.001
    noise_gyro_stddev_y: 0.001
    noise_gyro_stddev_z: 0.001
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0

gnss:
  id: gnss
  type: sensor.other.gnss
  blueprint: sensor.other.gnss
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  sensor_tick: 0.01

gnss_test:
  id: gnss_test
  type: sensor.other.gnss
  blueprint: sensor.other.gnss
  blueprint_attributes:
    noise_alt_stddev: 0.000005
    noise_lat_stddev: 0.000005
    noise_lon_stddev: 0.000005
    noise_alt_bias: 0.0
    noise_lat_bias: 0.0
    noise_lon_bias: 0.0
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 0.0

speedometer:
  id: speedometer
  type: sensor.other.speedometer
  blueprint: sensor.speedometer
  reading_frequency: 20

# The following sensors are illegal for CARLA Leaderboard 2.0.
camera_bev:
  id: camera_bev
  type: sensor.camera.rgb
  blueprint: sensor.camera.rgb
  blueprint_attributes:
    image_size_x: 640
    image_size_y: 480
    fov: 120
  x: 1.0
  y: 0.0
  z: 6.0
  roll: 0.0
  pitch: -90.0
  yaw: -90.0
  width: 640
  height: 480
  fov: 120

semantic_bev:
  id: semantic_bev
  type: sensor.camera.semantic_segmentation
  blueprint: sensor.camera.semantic_segmentation
  blueprint_attributes:
    image_size_x: 640
    image_size_y: 480
    fov: 120
  x: 1.0
  y: 0.0
  z: 6.0
  roll: 0.0
  pitch: -90.0
  yaw: -90.0
  width: 640
  height: 480
  fov: 120
