color_map:
- [0, 0, 0]                 # None
- [128, 64, 128]        # Road
- [244, 35, 232]      # Sidewalk
- [70, 70, 70]          # Building
- [102, 102, 156]     # Wall
- [190, 153, 153]     # Fence
- [153, 153, 153]     # Pole
- [250, 170, 30]      # Traffic light
- [220, 220, 0]       # Traffic sign
- [107, 142, 35]      # Vegetation
- [152, 251, 152]     # Terrain
- [70, 130, 180]      # Sky
- [220, 20, 60]       # Pedestrian
- [255, 0, 0]           # Rider
- [0, 0, 142]           # Car
- [0, 0, 70]              # Truck
- [0, 60, 100]          # Bus
- [0, 80, 100]          # Train
- [0, 0, 230]           # Motorcycle
- [119, 11, 32]         # Bicycle
- [110, 190, 160]     # Static
- [170, 120, 50]      # Dynamic
- [55, 90, 80]        # Other
- [45, 60, 150]       # Water
- [157, 234, 50]    # Road line
- [81, 0, 81]           # Ground
- [150, 100, 100]   # Bridge
- [230, 150, 140]   # Rail track
- [180, 165, 180]   # Guard rail
