path_agent_configs: carla_autopilot/configs/expert_agent.yaml
path_sensor_configs: carla_autopilot/configs/sensors.yaml
path_visualizer_configs: carla_autopilot/configs/visualize_binary.yaml

# Wandb
wandb_mode: online
entity: rambler
project: autopilot
name: data_collection
route: routes_training
route_subset: 0

# Sensor configuration
# sensor_ids: []
sensor_ids: [camera_front, camera_left, camera_right, camera_rear, lidar, semantic_bev]

# Data saving configuration
# Describe the way to parse the semantic segmentation data in bird-eye view
# path_save: /mnt/pool/rowena/expert_data/route_${route_subset}
path_save: ./data/expert_data/route_${route_subset}

# Control whether to save the route line
save_route: true

# Decide whether to visualize the data
visualize: false
