visualize: false
record: false
track: none
save_path: none
route_index: none
generate_data: true

# -------------------------------------------------------------
# Longitudinal Linear Regression Controller
# -------------------------------------------------------------

target_speed_slow: 5.0  # Speed at junctions, m/s

# -------------------------------------------------------------
# Longitudinal Linear Regression Controller
# -------------------------------------------------------------

# -------------------------------------------------------------
# Lateral PID Controller
# -------------------------------------------------------------

# -------------------------------------------------------------
# Privileged Route Planner
# -------------------------------------------------------------
privileged_route_planner:
